/**
 * generate.c
 *
 * Generates pseudorandom numbers in [0,MAX), one per line.
 *
 * Usage: generate n [s]
 *
 * where n is number of pseudorandom numbers to print
 * and s is an optional seed
 */
 
#define _XOPEN_SOURCE

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// upper limit on range of integers that can be generated
#define LIMIT 65536

int main(int argc, string argv[])
{
    // The program shows the user instruction for the input until there are two or three command-line arguments
    if (argc != 2 && argc != 3)
    {
        printf("Usage: ./generate n [s]\n");
        return 1;
    }

    // Covert the user's input from string to integer represented by variable "n" 
    int n = atoi(argv[1]);

    // When the user specify a "seed," the program calls the initialization function srand48
    // When the user does not specify a "seed," the initialization function returns default output
    if (argc == 3)
    {
        srand48((long) atoi(argv[2]));
    }
    else
    {
        srand48((long) time(NULL));
    }

    // Print on the screen a pseudorandom integer until there are n of them; 
    // Each integer is the fraction generated by drand48 times the upper limit specified atop
    for (int i= 0; i < n; i++)
    {
        printf("%i\n", (int) (drand48() * LIMIT));
    }

    // success
    return 0;
}
